##################################################################
# A Github action used to check pull requests on Web API
# More info at https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
##################################################################

name: Check pull request on Web API
on:
  push:
    branches: [main]
    paths:
      - "apps/web-api/**"
      - ".github/workflows/check-pull-request-web-api.yaml"
  pull_request:
    branches: [main]
    paths:
      - "apps/web-api/**"
      - ".github/workflows/check-pull-request-web-api.yaml"

jobs:
  check-linting:
    name: Check for linting errors in Web Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.6.0"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies and run linting
        run: |
          cd ./apps/web-api
          pnpm install
          pnpm lint

  run-tests:
    name: Runs all tests in Web Api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.6.0"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies, run tests, and upload coverage
        run: |
          cd ./apps/web-api
          pnpm install
          pnpm test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          directory: ./apps/web-api/coverage/
          flags: unittests

  build:
    name: Build the Web Api app via Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          cd ./apps/web-api
          docker build -t test-web-api .
